# -- BASIC CONFIGURATION -- #
spring:
  application:
    name: config-server
  jmx:
    default-domain: ${spring.application.name}

  # -- RABBIT MQ SERVER CONFIGURATION -- #
  # FOR SPRING CLOUD BUS - This configuration is only required to if RABBITMQ server is running on some different server
  #  If services are running on the same server where RABBITMQ server is running , there is no need to provide such configurations
  rabbitmq:
    host: 103.211.217.170
    username: sumitchouksey2315@gmail.com
    password: Shruti@300492
    port: 5672
  # --GITHUB CONFIGURATION -- #
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/sumitchouksey/configurations.git
          username: sumitchouksey2315@gmail.com
          password: Shruti@300492
  profiles:
    active: git # activate git profile
endpoints:
  jmx:
    domain: ${spring.jmx.default-domain}
server:
  port: 3172