# -- BASIC CONFIGURATION -- #
spring:
  application:
    name: config-server
  jmx:
    default-domain: ${spring.application.name}
  # -- RABBIT MQ SERVER CONFIGURATION -- #
  # FOR SPRING CLOUD BUS - This configuration is only required to if RABBITMQ server is running on some different server
  #  If services are running on the same server where RABBITMQ server is running , there is no need to provide such configurations
  rabbitmq:
    host: 54.225.9.1
    username: sumitchouksey2315@gmail.com
    password: Shruti@300492
    port: 5672

  # --SVN CONFIGURATION -- #
  cloud:
    config:
      server:
        svn:
          # SVN configuration details
          # Change it accordingly
          uri: svn Url for configurations
          username: svn userName
          password: svn password
          default-label: trunk
  profiles:
    active: subversion # activate svn profile

endpoints:
  jmx:
    domain: ${spring.jmx.default-domain}
server:
  port: 3172