# -- BASIC CONFIGURATION -- #
spring:
  application:
    name: config-server
  jmx:
    default-domain: ${spring.application.name}
  # -- RABBIT MQ SERVER CONFIGURATION -- #
  # FOR SPRING CLOUD BUS - This configuration is only required to if RABBITMQ server is running on some different server
  #  If services are running on the same server where RABBITMQ server is running , there is no need to provide such configurations
  rabbitmq:
    host: 54.225.9.1
    username: sumitchouksey2315@gmail.com
    password: Shruti@300492
    port: 5672

  # --LOCAL FILE SYSTEM CONFIGURATION -- #
  cloud:
    config:
      server:
        native:
          # Path to configuration directory
          # Change it accordingly
          search-locations: /d01/micro-services/configurations
  profiles:
    active: native # activate local profile
endpoints:
  jmx:
    domain: ${spring.jmx.default-domain}
server:
  port: 3172